### ISSUE TITLE
allow network-3.2

### ISSUE THREAD

**Issue by ysangkok** [Happstack/happstack-server-tls#3]
See

* https://github.com/commercialhaskell/stackage/issues/7381

The bump would be much appreciated! Let me know if you want a PR.

**Comment by ysangkok** [comment]
@stepcut Do you want me to send a PR for this bump?

**Comment by ddssff** [comment]
Send a PR and I'll mention it to stepcut.

**Comment by ysangkok** [comment]
@ddssff Submitted the PR
